export const GET_FORMATION_BY_FORMATEUR = "GET_FORMATION_BY_FORMATEUR";
export const DELETE_FORMATION = "DELETE_FORMATION";
export const ADD_FORMATION = "ADD_FORMATION";
export const GET_SINGLE_FORMATION = "GET_SINGLE_FORMATION";
export const UPDATE_FORMATION = "UPDATE_FORMATION"; 